package version_test

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/jverhoeks/deepdep/internal/version"
)

// Differential test against Python's own packaging library (the reference
// implementation of PEP 440), rather than against my reading of the spec.
// The oracle is generated by a script in the repo history and committed here.
func TestPEP440MatchesPackagingLibrary(t *testing.T) {
	var oracle struct {
		Satisfies [][3]any `json:"satisfies"` // [version, specifier, bool]
		Compare   [][3]any `json:"compare"`   // [a, b, -1|0|1]
	}
	b, err := os.ReadFile("testdata/pep440-oracle.json")
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(b, &oracle); err != nil {
		t.Fatal(err)
	}
	if len(oracle.Satisfies) < 300 || len(oracle.Compare) < 200 {
		t.Fatalf("oracle looks stubbed: %d satisfies, %d compare",
			len(oracle.Satisfies), len(oracle.Compare))
	}

	var mismatches int
	for _, c := range oracle.Satisfies {
		ver, spec, want := c[0].(string), c[1].(string), c[2].(bool)
		v, err := version.PEP440.Parse(ver)
		if err != nil {
			t.Errorf("Parse(%q): %v", ver, err)
			continue
		}
		got, err := version.PEP440.Satisfies(v, spec)
		if err != nil {
			t.Errorf("Satisfies(%q, %q): %v", ver, spec, err)
			continue
		}
		if got != want {
			mismatches++
			if mismatches <= 15 {
				t.Errorf("Satisfies(%q, %q) = %v, packaging says %v", ver, spec, got, want)
			}
		}
	}

	for _, c := range oracle.Compare {
		a, bb := c[0].(string), c[1].(string)
		want := int(c[2].(float64))
		x, err := version.PEP440.Parse(a)
		if err != nil {
			t.Errorf("Parse(%q): %v", a, err)
			continue
		}
		y, err := version.PEP440.Parse(bb)
		if err != nil {
			t.Errorf("Parse(%q): %v", bb, err)
			continue
		}
		got := version.PEP440.Compare(x, y)
		if sign(got) != want {
			mismatches++
			if mismatches <= 15 {
				t.Errorf("Compare(%q, %q) = %d, packaging says %d", a, bb, sign(got), want)
			}
		}
	}
	if mismatches > 0 {
		t.Errorf("%d total mismatches against the reference implementation", mismatches)
	}
}

func sign(n int) int {
	switch {
	case n < 0:
		return -1
	case n > 0:
		return 1
	}
	return 0
}
