package effective_test

import (
	"context"
	"testing"

	"github.com/jverhoeks/deepdep/internal/effective"
	"github.com/jverhoeks/deepdep/internal/source"
)

func ids(t *testing.T, r effective.EffectiveResolver, files ...source.File) map[string]bool {
	t.Helper()
	inst, err := r.Resolve(context.Background(), source.Static(files))
	if err != nil {
		t.Fatal(err)
	}
	out := map[string]bool{}
	for _, i := range inst {
		out[string(i.NodeID)] = true
		if i.DerivedFrom != "lockfile" {
			t.Errorf("%s DerivedFrom = %q, want lockfile", i.NodeID, i.DerivedFrom)
		}
	}
	return out
}

// Yarn v1's bespoke format: a descriptor line, then an indented version. A
// scope must survive, and one descriptor can list several ranges.
func TestYarnV1Lockfile(t *testing.T) {
	got := ids(t, effective.YarnLock{}, source.File{Path: "yarn.lock", Data: []byte(`
# THIS IS AN AUTOGENERATED FILE

lodash@^4.0.0, lodash@^4.17.0:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"

"@babel/core@^7.0.0":
  version "7.24.7"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.24.7.tgz"
`)})
	for _, want := range []string{"pkg:npm/lodash@4.17.21", "pkg:npm/%40babel/core@7.24.7"} {
		if !got[want] {
			t.Errorf("missing %s from %v", want, got)
		}
	}
	if len(got) != 2 {
		t.Errorf("got %d packages, want 2 — two ranges for one package are one install", len(got))
	}
}

// Berry is real YAML with a __metadata block. A v1 file is ALMOST valid YAML, so
// the format is sniffed rather than guessed by trying a parser.
func TestYarnBerryLockfile(t *testing.T) {
	got := ids(t, effective.YarnLock{}, source.File{Path: "yarn.lock", Data: []byte(`
__metadata:
  version: 8
  cacheKey: 10c0

"lodash@npm:^4.17.0":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"

"app@workspace:.":
  version: 0.0.0-use.local
  resolution: "app@workspace:."
`)})
	if !got["pkg:npm/lodash@4.17.21"] {
		t.Errorf("missing lodash from %v", got)
	}
	if got["pkg:npm/app@0.0.0-use.local"] {
		t.Error("a workspace member was reported as an installed dependency")
	}
}

// bun.lock is JSONC. Comments and trailing commas must be stripped, and a "//"
// inside a URL string must NOT start a comment and truncate the document.
func TestBunTextLockfile(t *testing.T) {
	got := ids(t, effective.BunLock{}, source.File{Path: "bun.lock", Data: []byte(`{
  // bun lockfile
  "lockfileVersion": 1,
  "packages": {
    "lodash": ["lodash@4.17.21", "https://registry.npmjs.org/lodash", {}, "sha512-x"],
    "@babel/core": ["@babel/core@7.24.7", {}, "sha512-y"],
  },
}`)})
	for _, want := range []string{"pkg:npm/lodash@4.17.21", "pkg:npm/%40babel/core@7.24.7"} {
		if !got[want] {
			t.Errorf("missing %s from %v", want, got)
		}
	}
}

// bun.lockb is binary with no published specification. Guessing at it would
// produce an answer nobody could check, so it must be left alone entirely and
// reported by Coverage instead.
func TestBunBinaryLockfileIsNotGuessedAt(t *testing.T) {
	got := ids(t, effective.BunLock{}, source.File{
		Path: "bun.lockb", Data: []byte{0x00, 0x01, 0xff, 0xfe, 'l', 'o', 'd'},
	})
	if len(got) != 0 {
		t.Errorf("got %v from a binary lockfile; it must be left to Coverage", got)
	}
}

// A malformed lockfile must not fail the whole scan.
func TestBunMalformedLockfileIsNotFatal(t *testing.T) {
	if got := ids(t, effective.BunLock{}, source.File{Path: "bun.lock", Data: []byte("{not json")}); len(got) != 0 {
		t.Errorf("got %v", got)
	}
}

func TestJSLockfilesIgnoreNodeModules(t *testing.T) {
	got := ids(t, effective.YarnLock{}, source.File{
		Path: "node_modules/x/yarn.lock",
		Data: []byte("leaked@^1.0.0:\n  version \"9.9.9\"\n"),
	})
	if len(got) != 0 {
		t.Errorf("a vendored lockfile was read: %v", got)
	}
}
